<?php

return array(
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
    "London",
    "Birmingham",
    "Leeds",
    "Glasgow",
    "Sheffield",
    "Bradford",
    "Liverpool",
    "Edinburgh",
    "Manchester",
    "Bristol",
    "Tokyo",
    "Yokohama",
    "Osaka",
    "Nagoya",
    "Sapporo",
    "Kobe",
    "Kyoto",
    "Fukuoka",
    "Kawasaki",
    "Saitama",
    "Beijing",
    "Shanghai",
    "Tianjin",
    "Guangzhou",
    "Shenzhen",
    "Chengdu",
    "Nanjing",
    "Wuhan",
    "Xi'an",
    "Hangzhou",
    "Paris",
    "Marseille",
    "Lyon",
    "Toulouse",
    "Nice",
    "Nantes",
    "Strasbourg",
    "Montpellier",
    "Bordeaux",
    "Lille",
    "Sydney",
    "Melbourne",
    "Brisbane",
    "Perth",
    "Adelaide",
    "Gold Coast",
    "Canberra",
    "Newcastle",
    "Wollongong",
    "Logan",
    "Mumbai",
    "Delhi",
    "Bangalore",
    "Hyderabad",
    "Ahmedabad",
    "Chennai",
    "Kolkata",
    "Surat",
    "Pune",
    "Jaipur",
    "Mexico",
    "Guadalajara",
    "Monterrey",
    "Puebla",
    "Toluca",
    "Tijuana",
    "Leon",
    "Ciudad Juarez",
    "Torreon",
    "San Luis Potosi",
    "Angeles",
    "Antipolo",
    "Bacolod",
    "Bacoor",
    "Bago",
    "Baguio",
    "Bais",
    "Balanga",
    "Batac",
    "Batangas",
    "Bayawan",
    "Baybay",
    "Bayugan",
    "Biñan",
    "Bislig",
    "Bogo",
    "Borongan",
    "Butuan",
    "Cabadbaran",
    "Cabanatuan",
    "Cabuyao",
    "Cadiz",
    "Cagayan de Oro",
    "Calamba",
    "Calapan",
    "Calbayog",
    "Caloocan",
    "Candon",
    "Canlaon",
    "Carcar",
    "Catbalogan",
    "Cauayan",
    "Cavite",
    "Cebu",
    "Cotabato",
    "Dagupan",
    "Danao",
    "Dapitan",
    "Dasmariñas",
    "Davao",
    "Digos",
    "Dipolog",
    "Dumaguete",
    "El Salvador",
    "Escalante",
    "Gapan",
    "General Santos",
    "General Trias",
    "Gingoog",
    "Guihulngan",
    "Himamaylan",
    "Ilagan",
    "Iligan",
    "Iloilo",
    "Imus",
    "Iriga",
    "Isabela",
    "Kabankalan",
    "Kidapawan",
    "Koronadal",
    "La Carlota",
    "Lamitan",
    "Laoag",
    "Lapu-Lapu",
    "Las Piñas",
    "Legazpi",
    "Ligao",
    "Lipa",
    "Lucena",
    "Maasin",
    "Mabalacat",
    "Makati",
    "Malabon",
    "Malaybalay",
    "Malolos",
    "Mandaluyong",
    "Mandaue",
    "Manila",
    "Marawi",
    "Marikina",
    "Masbate",
    "Mati",
    "Meycauayan",
    "Muñoz",
    "Muntinlupa",
    "Naga",
    "Navotas",
    "Olongapo",
    "Ormoc",
    "Oroquieta",
    "Ozamiz",
    "Pagadian",
    "Palayan",
    "Panabo",
    "Parañaque",
    "Pasay",
    "Pasig",
    "Passi",
    "Puerto Princesa",
    "Quezon",
    "Roxas",
    "Sagay",
    "Samal",
    "San Carlos",
    "San Fernando",
    "San Jose",
    "San Jose del Monte",
    "San Juan",
    "San Pablo",
    "San Pedro",
    "Santa Rosa",
    "Santiago",
    "Silay",
    "Sipalay",
    "Sorsogon",
    "Surigao",
    "Tabaco",
    "Tabuk",
    "Tacloban",
    "Tacurong",
    "Tagaytay",
    "Tagbilaran",
    "Taguig",
    "Tagum",
    "Talisay",
    "Tanauan",
    "Tandag",
    "Tangub",
    "Tanjay",
    "Tarlac",
    "Tayabas",
    "Toledo",
    "Trece Martires",
    "Tuguegarao",
    "Urdaneta",
    "Valencia",
    "Valenzuela",
    "Victorias",
    "Vigan",
    "Zamboanga"
);